import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import Nav from "@/components/Nav/Navbar";
import Footer from "@/components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <>
    <html lang="en">
     <AuthProvider>
          <body className={inter.className}>
            {/* <Providers> */}

              {/* <Nav/> */}
              <Nav/>
            
              {children}
            
            {/* </Providers> */}

            <Toaster />
          </body>
        </AuthProvider>
       
    </html>
    
     </>
  );
}
